[phases.setup]
nixPkgs = ["zbar", "libglvnd", "python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run consultor_precios.py --server.port $PORT --server.address 0.0.0.0"